//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Users.Laboratorist {
    
    
    public partial class dethReport {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HospitalManagementSystem.Admin.admins Master {
            get {
                return ((HospitalManagementSystem.Admin.admins)(base.Master));
            }
        }
    }
}
